# Generated by Django 2.2.3 on 2019-07-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('length', models.CharField(choices=[('H', 'Half Year'), ('Y', 'Full Year')], max_length=1)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('prerequisites', models.TextField()),
                ('exclusions', models.TextField()),
                ('faculty', models.TextField()),
                ('campus', models.CharField(choices=[('UTSG', 'St. George'), ('UTM', 'Mississauga'), ('UTSC', 'Scarborough')], max_length=4)),
                ('term', models.CharField(max_length=5)),
                ('breadth1', models.PositiveSmallIntegerField(choices=[(1, 'Creative and Cultural Representations'), (2, 'Thought, Belief, and Behaviour'), (3, 'Society and Its Institutions'), (4, 'Living Things and Their Environment'), (5, 'The Physical and Mathematical Universes')], null=True)),
                ('breadth2', models.PositiveSmallIntegerField(choices=[(1, 'Creative and Cultural Representations'), (2, 'Thought, Belief, and Behaviour'), (3, 'Society and Its Institutions'), (4, 'Living Things and Their Environment'), (5, 'The Physical and Mathematical Universes')], null=True)),
            ],
        ),
    ]
