# Generated by Django 2.2.4 on 2019-08-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['year', 'month']},
        ),
        migrations.RemoveField(
            model_name='term',
            name='name',
        ),
        migrations.AddField(
            model_name='term',
            name='month',
            field=models.SmallIntegerField(choices=[(1, 'Winter'), (5, 'Summer F'), (7, 'Summer S'), (9, 'Fall')], default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='year',
            field=models.SmallIntegerField(default=2019),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plannercourse',
            name='index',
            field=models.SmallIntegerField(),
        ),
    ]
