# Generated by Django 2.2.2 on 2019-07-04 02:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                                        primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                                        primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5)),
                ('plan',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='terms', to='main.Plan')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=3)),
                ('number', models.CharField(max_length=3)),
                ('length', models.CharField(
                    choices=[('H', 'Half Year'), ('Y', 'Full Year')],
                    max_length=1)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('prerequisites', models.TextField()),
                ('exclusions', models.TextField()),
                ('campus', models.CharField(
                    choices=[('UTSG', 'St. George'), ('UTM', 'Mississauga'),
                             ('UTSC', 'Scarborough')], max_length=4)),
                ('term', models.CharField(max_length=5)),
                ('breadth1', models.PositiveSmallIntegerField(
                    choices=[(1, 'Creative and Cultural Representations'),
                             (2, 'Thought, Belief, and Behaviour'),
                             (3, 'Society and Its Institutions'),
                             (4, 'Living Things and Their Environment'),
                             (5, 'The Physical and Mathematical Universes')],
                    null=True)),
                ('breadth2', models.PositiveSmallIntegerField(
                    choices=[(1, 'Creative and Cultural Representations'),
                             (2, 'Thought, Belief, and Behaviour'),
                             (3, 'Society and Its Institutions'),
                             (4, 'Living Things and Their Environment'),
                             (5, 'The Physical and Mathematical Universes')],
                    null=True)),
            ],
            options={
                'unique_together': {('department', 'number', 'term')},
            },
        ),
        migrations.CreateModel(
            name='PlannedCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                                        primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('course', models.CharField(max_length=9)),
                ('term',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='courses', to='main.Term')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('index', 'term')},
            },
        ),
    ]
