# Generated by Django 2.2.3 on 2019-07-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='ABC100Y1Y', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='plannedcourse',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='number',
        ),
    ]
